export type Machine = {
  id: string
  nom: string
  marque: string
  categorie: string
  technologie: string
  prixMin: number
  prixMax: number
  nbTechno: number
  formation: boolean
  sav: string
  garantie: string
  fabrication: string
  scoreROI: number
  badge?: string
}

export const machines: Machine[] = [
  {
    id: 'zemits-dermapure',
    nom: 'DermaPure Pro',
    marque: 'Zemits',
    categorie: 'Visage',
    technologie: 'Hydradermabrasion + LED + RF',
    prixMin: 3900,
    prixMax: 4900,
    nbTechno: 3,
    formation: true,
    sav: '48h',
    garantie: '2 ans',
    fabrication: 'EU',
    scoreROI: 92,
    badge: 'Meilleur rapport qualite/prix',
  },
  {
    id: 'zemits-verstand',
    nom: 'Verstand Ultra',
    marque: 'Zemits',
    categorie: 'Corps',
    technologie: 'Cavitation + RF + Vide',
    prixMin: 4500,
    prixMax: 5500,
    nbTechno: 3,
    formation: true,
    sav: '48h',
    garantie: '2 ans',
    fabrication: 'EU',
    scoreROI: 89,
  },
  {
    id: 'zemits-cryo',
    nom: 'CryoSlim 360',
    marque: 'Zemits',
    categorie: 'Minceur',
    technologie: 'Cryolipolyse',
    prixMin: 6900,
    prixMax: 8500,
    nbTechno: 1,
    formation: true,
    sav: '48h',
    garantie: '2 ans',
    fabrication: 'EU',
    scoreROI: 87,
  },
  {
    id: 'zemits-multi',
    nom: 'Neo Pro 7 en 1',
    marque: 'Zemits',
    categorie: 'Polyvalent',
    technologie: 'RF + Cavitation + LED + EMS + Cryotherapie + Ultrason + Vide',
    prixMin: 5200,
    prixMax: 6800,
    nbTechno: 7,
    formation: true,
    sav: '48h',
    garantie: '2 ans',
    fabrication: 'EU',
    scoreROI: 91,
    badge: 'Polyvalence maximale',
  },
  {
    id: 'cesam-jetpeel',
    nom: 'JetPeel Pro',
    marque: 'Cesam Esthetic',
    categorie: 'Visage',
    technologie: 'JetPeel + LED + Infusion actifs',
    prixMin: 6500,
    prixMax: 9000,
    nbTechno: 3,
    formation: true,
    sav: '72h',
    garantie: '1 an',
    fabrication: 'Israelien',
    scoreROI: 80,
  },
  {
    id: 'cesam-slim',
    nom: 'Twin Slim',
    marque: 'Cesam Esthetic',
    categorie: 'Corps',
    technologie: 'Cavitation + Radiofrequence',
    prixMin: 5800,
    prixMax: 7500,
    nbTechno: 2,
    formation: true,
    sav: '72h',
    garantie: '1 an',
    fabrication: 'Israelien',
    scoreROI: 75,
  },
  {
    id: 'lpg-cellu',
    nom: 'Cellu M6 Alliance',
    marque: 'LPG Systems',
    categorie: 'Minceur',
    technologie: 'Endermologie (mecanostimulation)',
    prixMin: 14000,
    prixMax: 20000,
    nbTechno: 1,
    formation: true,
    sav: '48h',
    garantie: '2 ans',
    fabrication: 'Francais',
    scoreROI: 78,
    badge: 'Reference minceur',
  },
  {
    id: 'lpg-lift6',
    nom: 'Lift 6',
    marque: 'LPG Systems',
    categorie: 'Visage',
    technologie: 'Endermologie visage',
    prixMin: 8000,
    prixMax: 12000,
    nbTechno: 1,
    formation: true,
    sav: '48h',
    garantie: '2 ans',
    fabrication: 'Francais',
    scoreROI: 72,
  },
  {
    id: 'europ-hifu',
    nom: 'HIFU Pro 7D',
    marque: "Europ'Esthetic",
    categorie: 'Visage',
    technologie: 'HIFU 7D multi-profondeurs',
    prixMin: 4200,
    prixMax: 6000,
    nbTechno: 1,
    formation: false,
    sav: '5 jours',
    garantie: '1 an',
    fabrication: 'Asiatique',
    scoreROI: 74,
  },
  {
    id: 'europ-cryo',
    nom: 'Cryo Elite',
    marque: "Europ'Esthetic",
    categorie: 'Minceur',
    technologie: 'Cryolipolyse double applicateurs',
    prixMin: 7500,
    prixMax: 10000,
    nbTechno: 1,
    formation: false,
    sav: '5 jours',
    garantie: '1 an',
    fabrication: 'Asiatique',
    scoreROI: 71,
  },
  {
    id: 'isi-multi',
    nom: 'ISI Multi-Tech 6 en 1',
    marque: 'ISI Spa',
    categorie: 'Polyvalent',
    technologie: 'RF + Cavitation + LED + Vide + EMS + Infrarouge',
    prixMin: 5500,
    prixMax: 7000,
    nbTechno: 6,
    formation: true,
    sav: '72h',
    garantie: '2 ans',
    fabrication: 'Francais',
    scoreROI: 83,
  },
]
